### ISSUE TITLE
Returns female names when asking for male names.

### ISSUE THREAD

**Issue by Pynamorous** [treyhunner/names#24]
Here is what I put to test this out after I noticed the issue:

for i in range(5):
    pop_name = names.get_full_name(gender="Male")
    print(pop_name)

Results:

Alvin Heller
George James
Wallace White
Lydia Pastrana
Donna Brubaker

**Comment by StephaneLefebvre** [comment]
Are you using an uppercase `M` for `gender="Male"` and if so does using `gender="male"` with a lowercase `m` change the result ?
I didn't manage to replicate the issue nevertheless ;

**Comment by Pynamorous** [comment]
I would have swore the docs said to use a capital, but I checked and it is lowercase, that's completely my bad I apologize, I will delete this report.
